### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by Divineaspect** [Xilef11/Runes-of-Wizardry#17]
This glorious mod is unfortunately so arcane that we can't find any documentation on it, and the in game book is also sadly lacking.

**Comment by Xilef11** [comment]
documentation is on the tooltip of the book. hold shift to see the extended tooltip with information on the required dusts and sacrifice. the book also allows you to place the patterns down (shift+right click on the center block with the rune selected). Tooltips are much easier to code than GUIs, but other than a visual representation of the pattern, there is not much information missing from the tooltip that was in the original mod's book

**Comment by Crazy-KSK** [comment]
the book needs the description "press shift to see more info"

**Comment by Xilef11** [comment]
will be in the next release (probably a in week or so). is there anything else missing?

**Comment by Divineaspect** [comment]
WIP runes should be labled as such.

about half of them have broken short descriptions.

Other then that we just want more awesome content.

**Comment by Xilef11** [comment]
Fixed in commit [7d6960a](https://github.com/Xilef11/runesofwizardry-classics/commit/7d6960ac674589ec4b0583e295b1fea71b578aa6) of the Classic Dusts pack (improved WIP documentation and added a config to disable WIP runes)
