### ISSUE TITLE
Rune of Sarlac crash 

### ISSUE THREAD

**Issue by Crazy-KSK** [Xilef11/Runes-of-Wizardry#18]
http://pastebin.com/iKrqeAUF happens when right clicking an active rune of sarlac with an empty hand
I also noticed that the radius seems too be one block too large as well since only 4 of the blocks in that area actually have dust in them it makes it very easy to walk into it on accident

**Comment by Xilef11** [comment]
single player or dedicated server? does it happen only with the rune of sarlacc?
