### ISSUE TITLE
Rune of Rebirth issues

### ISSUE THREAD

**Issue by Crazy-KSK** [Xilef11/Runes-of-Wizardry#20]
If the player is standing on top of the rune it makes a spawn egg "entity.Crazy-KSK.name" and all mobs become immobile and kind of rubber band when they try to move
sadly the egg does nothing =P

**Comment by Xilef11** [comment]
> all mobs become immobile and kind of rubber band when they try to move

this sounds like the server crashed but the client kept running. logs?

**Comment by Crazy-KSK** [comment]
the log looks like it should no errors sadly
the mobs do teleport a few blocks if I hit them and sometimes on their own too, I can kill the mobs with tnt too.
The server seems to be alive,  tps is fine at 30ms, blocks break fine too

**Comment by Crazy-KSK** [comment]
the log looks like it should no errors sadly
the mobs do teleport a few blocks if I hit them and sometimes on their own too, I can kill the mobs with tnt too.
The server seems to be alive, tps is fine at 30ms, blocks break fine too as long as I use tnt breaking blocks with my hands makes them reappear instantly

**Comment by Xilef11** [comment]
It looks like it tries to kill the player entity, but because players are handled differently than other entities, we get the wierd behaviour. (breaking blocks works in creative, and relogging or using /kill resets it). i'll just make sure the rune ignores players in the future.
