### ISSUE TITLE
Remove staff and activate with (shift) right-click?

### ISSUE THREAD

**Issue by Xilef11** [Xilef11/Runes-of-Wizardry#30]
That would make activation cheaper, but also makes accidental activation more likely (a problem if the "destroy dust on wrong pattern" option is active)

Also, Recipes for the book and pouches would need to be changed (and using "any dust" would require custom recipe handlers)

**Comment by renadi** [comment]
I would love this, would make a great addition to a more hardcore pack where even a couple gold nuggets might be overly expensive.

**Comment by Xilef11** [comment]
Implemented the change in v1.12.2-0.9.0
