### ISSUE TITLE
Etching

### ISSUE THREAD

**Issue by novasolarius** [Xilef11/Runes-of-Wizardry#33]
Dear Xilef11,

in the original Runic Dusts mod was a system in which one could etch channels of sorts into blocks. Once carved out, these channels could then be filled with liquid or soft materials. This system was originally used to mark the area to be affected by certain runes, though it could be used for decoration as well.

I kindly request that you look into the possibility of implementing such a system in your mod as well, even if it's only the decorative aspect.

**Comment by Xilef11** [comment]
I thought about it, but it is very unlikely that I will implement this feature for the following reasons:
* The only rune that used it was the rune of the mountain, and it ended up using a full clay block per "edge" block anyways.
* For the decorative aspect, Chisels & Bits allows to carve out blocks and fill them with arbitrary materials, including liquids. I suggest you check that out, as they probably have a much better/efficient implementation than what I could do.

Of course, it could have a use for future runes, so if someone wants to implement it, I'll happily accept the PR ;)

**Comment by novasolarius** [comment]
Very well, thanks for the response. I'll go ahead and close this now.
