### ISSUE TITLE
[1.12-0.8.3] Dedicated Server Crash

### ISSUE THREAD

**Issue by Alaberti** [Xilef11/Runes-of-Wizardry#36]
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/statemap/IStateMapper
Crash Report: https://pastebin.com/Bqc0xyvp

Forge 4443
Runes of Wizardry Classics 1.12-0.5.2

**Comment by Xilef11** [comment]
Fixed in v1.12-0.8.4. thanks for the report!

You can download from GitHub, I'm having trouble uploading to Curse right now.
