### ISSUE TITLE
1.12 Items appearing in other Creative tabs

### ISSUE THREAD

**Issue by Divineaspect** [Xilef11/Runes-of-Wizardry#38]
The small plant ball, large plant ball, and inscriptions are appearing in other mod's creative tabs.

**Comment by Xilef11** [comment]
Fixed in v0.8.6.

you can download from GitHub immediately ([here](https://github.com/Xilef11/Runes-of-Wizardry/releases/download/v1.12-0.8.6/Runes-of-Wizardry-1.12-0.8.6.jar)), it should be on Curse later today.
