### ISSUE TITLE
I want version 1.6.4 of this MOD

### ISSUE THREAD

**Issue by YutoNishimura-v2** [Xilef11/Runes-of-Wizardry#4]
Hello!
Thank you very much for making MOD!
so,I want to play this MOD.
But , I was not able to download this MOD of version 1.6.4.
So, please tell me the downloading link.
Or , Please spend it for my email.
Thank you.

Mail　address : midoritouhou@gmail.com

**Comment by Xilef11** [comment]
I am not aware that there is a version for 1.6.4 avaliable.
