### ISSUE TITLE
Runes of Wizardry Crash at Launch

### ISSUE THREAD

**Issue by SpaceRiceBowl** [Xilef11/Runes-of-Wizardry#40]
[crash-2017-08-24_16.59.28-client.txt](https://github.com/Xilef11/Runes-of-Wizardry/files/1250244/crash-2017-08-24_16.59.28-client.txt)

**Comment by Xilef11** [comment]
You're using a broken version of the Classic Dusts pack (runesofwizardry_classics 1.10.2-0.4.3-b1) which I have removed from both CurseForge and GitHub. please use [v1.10.2-0.4.3-b2](https://github.com/Xilef11/runesofwizardry-classics/releases/download/v1.10.2-0.4.3-b2/RunesofWizardry-Classics-1.10.2-0.4.3-b2.jar) instead.
