### ISSUE TITLE
CORRUPT SAVE when using Rune of Dawn (1.12.2)

### ISSUE THREAD

**Issue by Atskadan** [Xilef11/Runes-of-Wizardry#45]
https://pastebin.com/ANGyHZZz

Seemed to happen after walking over the particle effect it creates. 

Modlist: https://pastebin.com/dtSBX48J

**Comment by Atskadan** [comment]
Update: attempting to enter the world again after this has happened causes the game to crash with no warning. Thankfully this was in a test world, but this appears to be a major bug.

**Comment by Xilef11** [comment]
Hi

I can't reproduce this after updating Forge, etc. please try the new version of the mods, which should be up on CurseForge in a few minutes.
