### ISSUE TITLE
Two bugs in 1.7.10 backport

### ISSUE THREAD

**Issue by ghost** [Xilef11/Runes-of-Wizardry#5]
1) (minor and mostly annoying, but not game breaking): Dust can't be broken except by removing the block under it.

2) (The big one): Server crashes if "dye" button is pressed in arcane dye and there is no dust in it.

**Comment by Xilef11** [comment]
1): Dust must be removed by right-clicking with an empty hand (on each dust square). When I figure out how, it will be with left-click.
2): i'll look into it

**Comment by ghost** [comment]
Ahh, gotcha.

Thanks!

**Comment by ghost** [comment]
[Just realised the crash log would probably help](http://pastebin.com/MnWEUqKj)

After looking it over it looks like something went wonky with WRCBE but it did happen right as I clicked "dye" so I dunno.

**Comment by Xilef11** [comment]
that log is probably for something else, but there was indeed an issue with this.

**Comment by ghost** [comment]
Oh, whoops.

Turns out that log is from Oct 30, so that's a thing.
Sorry for the useless info.
