### ISSUE TITLE
Unable to get game to start

### ISSUE THREAD

**Issue by ZarenGaming72** [Xilef11/Runes-of-Wizardry#50]
I am able to start the base mod to work, but when I add the classic pack my game is unable to start. I might have put the file in the wrong area, but I haven't seen any instructions on how to install the mod addons properly, I just put the jar file into my mods folder and hoped it would work, if I'm doing something wrong I would like it if someone could please tell me. Thanks!

   -Zaren

(Edit, fixed it by downloading a non broken version, went into closed issues)

**Comment by Xilef11** [comment]
Which version(s) did you try? What was the error/log? If there is a broken version I'd like to be able to fix it...
