### ISSUE TITLE
Placing dust deletes block above target

### ISSUE THREAD

**Issue by tyon2006** [Xilef11/Runes-of-Wizardry#52]
When I apply a dust to a block, if a block is above it, it will delete the block above it and then put th dust in its place. The block is not dropped, but rather, simply disappears and there is a single dust on top of the block I clicked. It will even delete bedrock. 

Latest version of dusts, Forge 2847

See example below. Each block in the bottom row was right clicked with dust in hand. 

![image](https://user-images.githubusercontent.com/26413035/68987752-e4333100-07fa-11ea-9f59-68ca77bac8a8.png)

![image](https://user-images.githubusercontent.com/26413035/68987758-f319e380-07fa-11ea-848a-4433f5095768.png)

**Comment by Xilef11** [comment]
Fixed by [0d6d991d0f](https://github.com/Xilef11/Runes-of-Wizardry/commit/0d6d991d0ff82c62e74ca7dc37e5580a227e6f43). Will be in the next release
